### ISSUE TITLE
"required" over an array of objects is ignored

### ISSUE THREAD

**Issue by oleiade** [dantothefuture/svarog#23]
Hi 👋🏻 

First, I want to say thank you for putting this library together, it's already proved super useful to me, and makes me sleep better at night 🙏🏻 

I've recently been running into what I think might be a limitation of svarog though, and wanted to check if it was one indeed, or if there simply was an issue between the chair and the keyboard.

It seems that array of objects definitions ignore the `required` properties. I've looked into the currently described limitations, but couldn't figure out if it was the expected behavior in the current state of the tool. 

For instance, validating:

```
{
  "stuffed": [
    {
      "foo": "hello, I'm Pierrot le foo"
    }
  ]
}
```  

with the following schema
```
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "Stuff",
    "type": "object",
    "properties": {
        "stuffed": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "foo": {
                        "type": "string"
                    },
                    "bar": {
                        "type": "string"
                    }
                },
                "required": [
                    "foo",
                    "bar"
                ]
            }
        }
    },
```

In the context of this security rules
```
match /stuff/{stuffID} {
  allow create: if isValid("Stuff");
```

I would expect the `isValid("Stuff")` call to fail, and the security rules making the document creation also fail as a result, because `bar` was not present. It is the behavior shown by external JSON Schema validators. Is it Svarog's expected behavior? Is it a known limitation? How can I contribute to make this behavior supported if that's the case?

Cheers!

**Comment by pheekus** [comment]
This is such a well-written issue I feel bad telling you that what you’re describing can’t be done in CEL at the moment :)

To validate an array of arbitrary size, we’d need a way to iterate over it and, sadly, the subset of CEL used in Security Rules does not provide one at the moment (a team member has mentioned on Reddit they were considering it a year ago, but I haven’t heard of any progress since). Recursive calls aren’t supported, so that’s off the table, plus there’s a call depth limit of 20, which puts even more constraints on the generated code.

So for now Svarog supports only tuple validation for arrays. However, if you have a solution (or an idea) – I’ll be more than happy to look into and implement it because it’s been the most prominent issue with this tool so far.

**Comment by oleiade** [comment]
Hehe, no worries at all! Thanks a lot for taking the time to answer in detail 🤝 though. I understand better why it is not possible then, and I've learned something about CEL on top of that. Here's to being able to do this kind of checks in the future 🦖 🦕 Cheers!
